def test_this_func():
    print('This is running and expecting a raise Exception')
    # raise Exception('haha this fails')

test_this_func()